services:
  - type: web
    name: jobboard-frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html